# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a3e2f31e07d0a7fc4b485ab87527f1a8893c7e9078501064158ac21352dfb341a87d3054d460123c39a5825db5c7f166b1cb6a933d3a7b8be6d69210efa5115

test:
  secret_key_base: b77e78e96d3cf2a183606ec6a368a94bf2031e63cc20905b0ca644ee328f2347d419fad98e27650a6b9b3c13382a8ab398af313fd474f9090ef1ab4d3529662f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
